### ISSUE TITLE
A realted project you might want to review

### ISSUE THREAD

**Issue by ianozsvald** [intuitivetextmining/d3fdgraph#1]
Hi Tariq. Thanks for your lightning talk at PyDataLondon.

I've been playing with the Altair data viz tool (using vega to replace matplotlib), I gave a demo during my PyLondinium talk this weekend. https://altair-viz.github.io/user_guide/ecosystem.html

Whilst digging I found that they have a NetworkX integration including some snazzy interactive graphs. https://github.com/Zsailer/nx_altair

Personally I'd love to see a NetworkX connector, building graphs in nx is something I've done for >10 yrs so using that familiar interface and then visualising it with d3fdgraph (or nx_altair I guess) would be lovely.

I'm going to mention your library in one of my future thoughts&jobs emails, thanks for sharing it!

**Comment by intuitivetextmining** [comment]
hey ian - thanks for having me! .. and also for the pointer, I didn't know about the new altair graph plots .. looks like jupyterlab will have it soon, if not already.

thanks for the mention too - this is my first ever library that I've put on pip ever!
